function shiftROIs_CALLBACK(src,evnt,parameters)
%shiftROIs_CALLBACK.m Callback to shift all ROIs 
%
%INPUTS
%parameters - parameters structure of data
%
%ASM 11/13

%get parameters
parameters = get(parameters.ROIFig,'UserData');

%set to shifting
parameters.shifting = true;

if isfield(parameters,'xShift')
    delete(parameters.xShiftUp,parameters.xShift,parameters.xShiftDown,...
        parameters.yShift,parameters.yShiftDown,parameters.yShiftUp,...
        parameters.confirmROIShift,parameters.xShiftText,parameters.yShiftText,...
        parameters.rotate,parameters.rotateUp,parameters.rotateDown,...
        parameters.rotateText);
end

%add buttons
parameters.xShift = uicontrol('Style','edit','Units','Normalized','Position',...
    [0.16 0.46 0.02 0.03],'String','0','Callback',...
    {@shiftROIButtons_CALLBACK,parameters},'FontSize',15);
parameters.xShiftUp = uicontrol('Style','pushbutton','Units','Normalized','Position',...
    [0.185 0.46 0.015 0.03],'String','>',...
    'Callback',{@shiftROIButtons_CALLBACK,parameters},'FontSize',20);
parameters.xShiftDown = uicontrol('Style','pushbutton','Units','Normalized','Position',...
    [0.14 0.46 0.015 0.03],'String','<','Callback',...
    {@shiftROIButtons_CALLBACK,parameters},'FontSize',20);
parameters.xShiftText = uicontrol('Style','text','Units','Normalized',...
    'Position',[0.1 0.46 0.035 0.03],'String','xShift','FontSize',15,...
    'BackgroundColor',get(parameters.ROIFig,'Color'));
parameters.yShift = uicontrol('Style','edit','Units','Normalized','Position',...
    [0.16 0.41 0.02 0.03],'String','0','Callback',...
    {@shiftROIButtons_CALLBACK,parameters},'FontSize',15);
parameters.yShiftUp = uicontrol('Style','pushbutton','Units','Normalized','Position',...
    [0.185 0.41 0.015 0.03],'String','>','Callback',...
    {@shiftROIButtons_CALLBACK,parameters},'FontSize',20);
parameters.yShiftDown = uicontrol('Style','pushbutton','Units','Normalized','Position',...
    [0.14 0.41 0.015 0.03],'String','<','Callback',...
    {@shiftROIButtons_CALLBACK,parameters},'FontSize',20);
parameters.yShiftText = uicontrol('Style','text','Units','Normalized',...
    'Position',[0.1 0.41 0.035 0.03],'String','yShift','FontSize',15,...
    'BackgroundColor',get(parameters.ROIFig,'Color'));
parameters.rotate = uicontrol('Style','edit','Units','Normalized','Position',...
    [0.16 0.36 0.02 0.03],'String','0','Callback',...
    {@shiftROIButtons_CALLBACK,parameters},'FontSize',15);
parameters.rotateUp = uicontrol('Style','pushbutton','Units','Normalized','Position',...
    [0.185 0.36 0.015 0.03],'String','>','Callback',...
    {@shiftROIButtons_CALLBACK,parameters},'FontSize',20);
parameters.rotateDown = uicontrol('Style','pushbutton','Units','Normalized','Position',...
    [0.14 0.36 0.015 0.03],'String','<','Callback',...
    {@shiftROIButtons_CALLBACK,parameters},'FontSize',20);
parameters.rotateText = uicontrol('Style','text','Units','Normalized',...
    'Position',[0.1 0.36 0.035 0.03],'String','Rotate','FontSize',15,...
    'BackgroundColor',get(parameters.ROIFig,'Color'));
parameters.confirmROIShift = uicontrol('Style','PushButton','Units','Normalized','Position',...
    [0.1 0.255 0.1 0.095],'String','Confirm Shift','Callback',...
    {@confirmROIShift_CALLBACK,parameters});

%save old parameters
parameters.oldROIs = parameters.ROIs;
parameters.oldCentroid = parameters.centroid;
parameters.oldEdgeInd = parameters.edgeInd;


%save updated parameters
set(parameters.ROIFig,'UserData',parameters);